version: '3'
services:
  jest:
    build: .
    command: yarn test
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  build:
    build: .
    command: yarn build 
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  server:
    build: .
    command: node server.js
    depends_on:
      - build
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    networks: 
      - backend
      
networks:
    backend:
        driver: bridge